### ISSUE TITLE
Missing graphics

### ISSUE THREAD

**Issue by hafklin** [dpvdberg/IntroductionToCryptology#1]
Hey, first of all thanks a lot for publishing this summary, it will be insanely helpful in preparation for the exam. Most of the images mentioned in the main.tex file are however missing, any way they could be added as well? 
If the images simply do not yet exist, let me know and I'd be willing to assist you in creating them. :)

Keep it up,
Linus

**Comment by dpvdberg** [comment]
Hi! Thanks for noticing. 

Almost all the writing was done by @svdeerenbeemt, so credits go to her :) 

I'll add the pictures asap.

**Comment by hafklin** [comment]
Great, thanks a lot!
@svdeerenbeemt
